name: Build

on:
  push:
    branches:
    - master
    - maci-*
  pull_request:
    branches:
    - '*'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

        golang_version: [1.16.4]
        java_version: ['15', '16']
        python_version: [3.6, 3.7, 3.8, 3.9]
        rust_version: [stable]

    env:
      OS: ${{ matrix.os }}

      GOLANG_VERSION: ${{ matrix.golang_version }}
      JAVA_VERSION: ${{ matrix.java_version }}
      PYTHON_VERSION: ${{ matrix.python_version }}
      RUST_VERSION: ${{ matrix.rust_version }}

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python_version }}
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust_version }}
        override: true
        components: rustfmt
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: ${{ matrix.java_version }}
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.golang_version }}
    - name: Install Python dependencies
      run: pip install codecov tox tox-gh-actions
    - name: Run Tox
      run: tox
    - name: Upload coverage to Codecov
      if: ${{ success() }}
      uses: codecov/codecov-action@v1
      with:
        env_vars: OS,GOLANG_VERSION,JAVA_VERSION,OS,PYTHON_VERSION,RUST_VERSION

  precommit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Python dependencies
      run: pip install tox
    - name: Run Tox
      run: tox -e pre-commit
